In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [4]:
np.random.seed(0)
indices = np.random.permutation(len(iris_x))

In [8]:
iris_x_train = iris_x[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_x_test = iris_x[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
# iris_x_train.dtype

In [12]:
knn.fit(iris_x_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [13]:
knn.predict(iris_x_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

In [14]:
iris_y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])